### ISSUE TITLE
TypeId in Attributes Documentation

### ISSUE THREAD

**Issue by latonz** [charlesdevandiere/xmldoc2md#15]
Thank you for the great tool!

For attribute classes an inherited `TypeId` property shows up in the documentation.
Would be nice, if this could be removed as for simple classes or if at least there could be an option to remove it.

```csharp
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public MyAttribute : Attribute
{
}
```

**Comment by charlesdevandiere** [comment]
Thank you for your interest in this project.

When looking at Microsoft's Obsolete attribute documentation, one can see the TypeId property. Therefore, I think hiding the TypeId is undesirable.
