### ISSUE TITLE
Error generating `index.md` when type does not have an explicit namespace.

### ISSUE THREAD

**Issue by TimothyMakkison** [charlesdevandiere/xmldoc2md#28]
Line `File.WriteAllText(Path.Combine(@out, $"{indexPageName}.md"), indexPage.ToString());` in `program` generates the error: `Unable to generate documentation: Object reference not set to an instance of an object.` when converting a type without a namespace.

To reproduce create a type outside of a namespace scope and run this tool.
```C#
public class MyClass
{
}
```

**Comment by charlesdevandiere** [comment]
Fixed in #35 for v5.0.0
