### ISSUE TITLE
Please add support for <paramref> tags

### ISSUE THREAD

**Issue by azurefx** [charlesdevandiere/xmldoc2md#32]
Hello, I encountered a problem when generating documentations with `<paramref>` tags.

Currently xmldoc2md treats these tags as "regular" tags and takes innerText instead of the `name` attribute. This means that if there is such a comment:

```csharp
// <summary>
/// See parameter <paramref name="myParam"/>.
/// </summary>
```

Then the generated document looks like this:

```markdown
See parameter .
```

The relevant code looks like here:

https://github.com/charlesdevandiere/xmldoc2md/blob/58bbe3154d9dd6fdddeb2212e40f6e58f7960a9f/src/XMLDoc2Markdown/TypeDocumentation.cs#L197-L210

Maybe adding a switch case will solve this problem?

**Comment by charlesdevandiere** [comment]
Fixed in #35 for v5.0.0
